openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      tags:
        - tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      tags:
        - tasks
      requestBody:
        description: The task to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: The created task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/{id}:
    patch:
      summary: Update a task
      tags:
        - tasks
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: uint
          description: ID of the task to update
      requestBody:
        description: The task to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: The updated task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    delete:
      summary: Delete a task
      tags:
        - tasks
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: uint
          description: ID task to delete
      responses:
        '204':
          description: Task deleted successfully
  /users:
    get:
      summary: Get all users
      tags:
        - users
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      tags:
        - users
      requestBody:
        description: The user to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request body
  /users/{id}:
    patch:
      summary: Update a user
      tags:
        - users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: uint
          description: User ID
      requestBody:
        description: The user to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request body
        '404':
          description: User not found
    delete:
      summary: Delete a user
      tags:
        - users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: uint
          description: User ID
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found
  /users/{id}/tasks:
    get:
      summary: Get task by user id
      tags:
        - tasks
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: uint
          required: true
          description: ID user
      responses:
        '202':
          description: Task user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: uint
        task:
          type: string
        is_done:
          type: boolean
        userId:
          type: integer
          format: uint
    User:
      type: object
      properties:
        ID:
          type: integer
          format: uint
          description: User ID
        Email:
          type: string
          description: User email
        Password:
          type: string
          description: User password
        CreatedAt:
          type: string
          format: date-time
          description: Creation timestamp
        UpdatedAt:
          type: string
          format: date-time
          description: Last update timestamp
    NewUser:
      type: object
      properties:
        Email:
          type: string
          description: User email
        Password:
          type: string
          description: User password
      required:
        - Email
        - Password
    UpdateUser:
      type: object
      properties:
        Email:
          type: string
          description: User email
        Password:
          type: string
          description: User password